import 'server-only';

type ColumnSpec = readonly [
  table: string,
  name: string,
  position: number | null,
  type: string,
  notNull: boolean,
  defaultExpression: string | null,
];

export const PERSON_SCHEMA_COLUMNS = [
  ['AuditLog', 'entityType', null, 'character varying(40)', false, null],
  ['AuditLog', 'entityId', null, 'character varying(128)', false, null],
  ['AuditEncryptionKeyVersion', 'version', null, 'integer', true, null],
  [
    'AuditEncryptionKeyVersion',
    'algorithm',
    null,
    'character varying(32)',
    true,
    "'AES-256-GCM'::text",
  ],
  [
    'AuditEncryptionKeyVersion',
    'firstUsedAt',
    null,
    'timestamp(3) without time zone',
    true,
    'CURRENT_TIMESTAMP',
  ],
  ['Person', 'id', null, 'text', true, null],
  ['Person', 'nickname', null, 'character varying(80)', false, null],
  ['Person', 'normalizedNickname', null, 'character varying(160)', false, null],
  ['Person', 'firstName', null, 'character varying(100)', false, null],
  [
    'Person',
    'normalizedFirstName',
    null,
    'character varying(200)',
    false,
    null,
  ],
  ['Person', 'lastName', null, 'character varying(100)', false, null],
  ['Person', 'normalizedLastName', null, 'character varying(200)', false, null],
  ['Person', 'sortName', null, 'character varying(401)', true, null],
  ['Person', 'birthDate', null, 'date', false, null],
  [
    'Person',
    'structureStatus',
    null,
    '"PersonStructureStatus"',
    true,
    "'OUTSIDE_STRUCTURE'::PersonStructureStatus",
  ],
  ['Person', 'version', null, 'integer', true, '1'],
  [
    'Person',
    'createdAt',
    null,
    'timestamp(3) without time zone',
    true,
    'CURRENT_TIMESTAMP',
  ],
  ['Person', 'updatedAt', null, 'timestamp(3) without time zone', true, null],
  ['PersonEmail', 'id', null, 'text', true, null],
  ['PersonEmail', 'personId', null, 'text', true, null],
  ['PersonEmail', 'email', null, 'character varying(320)', true, null],
  [
    'PersonEmail',
    'normalizedEmail',
    null,
    'character varying(320)',
    true,
    null,
  ],
  ['PersonEmail', 'label', null, 'character varying(40)', true, null],
  ['PersonEmail', 'isPrimary', null, 'boolean', true, 'false'],
  ['PersonEmail', 'version', null, 'integer', true, '1'],
  [
    'PersonEmail',
    'createdAt',
    null,
    'timestamp(3) without time zone',
    true,
    'CURRENT_TIMESTAMP',
  ],
  [
    'PersonEmail',
    'updatedAt',
    null,
    'timestamp(3) without time zone',
    true,
    null,
  ],
  ['PersonPhone', 'id', null, 'text', true, null],
  ['PersonPhone', 'personId', null, 'text', true, null],
  ['PersonPhone', 'phone', null, 'character varying(40)', true, null],
  ['PersonPhone', 'normalizedPhone', null, 'character varying(16)', true, null],
  ['PersonPhone', 'label', null, 'character varying(40)', true, null],
  ['PersonPhone', 'isPrimary', null, 'boolean', true, 'false'],
  ['PersonPhone', 'version', null, 'integer', true, '1'],
  [
    'PersonPhone',
    'createdAt',
    null,
    'timestamp(3) without time zone',
    true,
    'CURRENT_TIMESTAMP',
  ],
  [
    'PersonPhone',
    'updatedAt',
    null,
    'timestamp(3) without time zone',
    true,
    null,
  ],
  ['PersonSocialProfile', 'id', null, 'text', true, null],
  ['PersonSocialProfile', 'personId', null, 'text', true, null],
  [
    'PersonSocialProfile',
    'networkKey',
    null,
    'character varying(40)',
    true,
    null,
  ],
  [
    'PersonSocialProfile',
    'identifier',
    null,
    'character varying(100)',
    false,
    null,
  ],
  [
    'PersonSocialProfile',
    'normalizedIdentifier',
    null,
    'character varying(100)',
    false,
    null,
  ],
  [
    'PersonSocialProfile',
    'profileUrl',
    null,
    'character varying(2048)',
    false,
    null,
  ],
  [
    'PersonSocialProfile',
    'normalizedProfileUrl',
    null,
    'character varying(2048)',
    false,
    null,
  ],
  [
    'PersonSocialProfile',
    'normalizedProfileUrlHash',
    null,
    'character(64)',
    false,
    null,
  ],
  ['PersonSocialProfile', 'label', null, 'character varying(40)', true, null],
  ['PersonSocialProfile', 'isPrimary', null, 'boolean', true, 'false'],
  ['PersonSocialProfile', 'version', null, 'integer', true, '1'],
  [
    'PersonSocialProfile',
    'createdAt',
    null,
    'timestamp(3) without time zone',
    true,
    'CURRENT_TIMESTAMP',
  ],
  [
    'PersonSocialProfile',
    'updatedAt',
    null,
    'timestamp(3) without time zone',
    true,
    null,
  ],
  [
    'PersonDeletionTombstone',
    'personId',
    null,
    'character varying(128)',
    true,
    null,
  ],
  [
    'PersonDeletionTombstone',
    'deletionOperationId',
    null,
    'character varying(191)',
    true,
    null,
  ],
  [
    'PersonDeletionTombstone',
    'deletedAt',
    null,
    'timestamp(3) without time zone',
    true,
    'CURRENT_TIMESTAMP',
  ],
  ['AuditFieldChange', 'id', null, 'text', true, null],
  ['AuditFieldChange', 'auditLogId', null, 'text', true, null],
  ['AuditFieldChange', 'entityType', null, 'character varying(40)', true, null],
  ['AuditFieldChange', 'entityId', null, 'character varying(128)', true, null],
  ['AuditFieldChange', 'sectionKey', null, 'character varying(64)', true, null],
  ['AuditFieldChange', 'fieldKey', null, 'character varying(100)', true, null],
  ['AuditFieldChange', 'recordId', null, 'character varying(128)', false, null],
  [
    'AuditFieldChange',
    'changeType',
    null,
    '"AuditFieldChangeType"',
    true,
    null,
  ],
  [
    'AuditFieldChange',
    'valueMode',
    null,
    '"AuditValueStorageMode"',
    true,
    null,
  ],
  [
    'AuditFieldChange',
    'beforeValue',
    null,
    'character varying(512)',
    false,
    null,
  ],
  [
    'AuditFieldChange',
    'afterValue',
    null,
    'character varying(512)',
    false,
    null,
  ],
  ['AuditFieldChange', 'valuesCiphertext', null, 'bytea', false, null],
  ['AuditFieldChange', 'valuesIv', null, 'bytea', false, null],
  ['AuditFieldChange', 'valuesAuthTag', null, 'bytea', false, null],
  ['AuditFieldChange', 'valueKeyVersion', null, 'integer', false, null],
  ['AuditFieldChange', 'beforeHash', null, 'character(64)', false, null],
  ['AuditFieldChange', 'afterHash', null, 'character(64)', false, null],
  [
    'AuditFieldChange',
    'createdAt',
    null,
    'timestamp(3) without time zone',
    true,
    null,
  ],
] as const satisfies readonly ColumnSpec[];

export const PERSON_SCHEMA_ENUMS = [
  ['PersonStructureStatus', 'IN_STRUCTURE', 1],
  ['PersonStructureStatus', 'OUTSIDE_STRUCTURE', 2],
  ['AuditFieldChangeType', 'CREATE', 1],
  ['AuditFieldChangeType', 'UPDATE', 2],
  ['AuditFieldChangeType', 'DELETE', 3],
  ['AuditValueStorageMode', 'PLAIN', 1],
  ['AuditValueStorageMode', 'ENCRYPTED', 2],
  ['AuditValueStorageMode', 'NONE', 3],
  ['AuditAction', 'PERSON_CREATE', null],
  ['AuditAction', 'PERSON_UPDATE', null],
  ['AuditAction', 'PERSON_DELETE', null],
  ['AuditCategory', 'PERSON', null],
] as const;
