import 'server-only';

type CheckSpec = readonly [name: string, table: string, expression: string];
type ForeignKeySpec = readonly [
  name: string,
  table: string,
  columns: string,
  referencedTable: string,
  referencedColumns: string,
  onDelete: string,
  onUpdate: string,
];
type IndexSpec = readonly [
  name: string,
  table: string,
  method: 'btree' | 'gin',
  unique: boolean,
  columns: string,
  opclasses: string,
  predicate: string | null,
];
type FunctionSpec = readonly [
  name: string,
  identityArguments: string,
  resultType: string,
  securityDefiner: boolean,
  configuration: string,
];
type TriggerSpec = readonly [
  name: string,
  table: string,
  functionName: string,
  typeMask: number,
];

export const PERSON_SCHEMA_CHECKS = [
  [
    'AuditLog_entity_subject_pair_check',
    'AuditLog',
    '("entityType" IS NULL) = ("entityId" IS NULL)',
  ],
  [
    'AuditLog_person_event_shape_check',
    'AuditLog',
    "((\"action\"::text IN ('PERSON_CREATE', 'PERSON_UPDATE', 'PERSON_DELETE') AND \"category\"::text = 'PERSON' AND \"stream\"::text = 'IDENTITY' AND \"entityType\" = 'PERSON' AND \"entityId\" IS NOT NULL) OR (\"action\"::text NOT IN ('PERSON_CREATE', 'PERSON_UPDATE', 'PERSON_DELETE') AND \"category\"::text <> 'PERSON'))",
  ],
  [
    'AuditEncryptionKeyVersion_version_check',
    'AuditEncryptionKeyVersion',
    '"version" >= 1',
  ],
  [
    'AuditEncryptionKeyVersion_algorithm_check',
    'AuditEncryptionKeyVersion',
    '"algorithm" = \'AES-256-GCM\'',
  ],
  ['Person_version_check', 'Person', '"version" >= 1'],
  [
    'Person_nickname_pair_check',
    'Person',
    '("nickname" IS NULL AND "normalizedNickname" IS NULL) OR ("nickname" IS NOT NULL AND "normalizedNickname" IS NOT NULL AND "nickname" = btrim("nickname") AND "nickname" <> \'\' AND "normalizedNickname" = btrim("normalizedNickname") AND "normalizedNickname" <> \'\')',
  ],
  [
    'Person_first_name_pair_check',
    'Person',
    '("firstName" IS NULL AND "normalizedFirstName" IS NULL) OR ("firstName" IS NOT NULL AND "normalizedFirstName" IS NOT NULL AND "firstName" = btrim("firstName") AND "firstName" <> \'\' AND "normalizedFirstName" = btrim("normalizedFirstName") AND "normalizedFirstName" <> \'\')',
  ],
  [
    'Person_last_name_pair_check',
    'Person',
    '("lastName" IS NULL AND "normalizedLastName" IS NULL) OR ("lastName" IS NOT NULL AND "normalizedLastName" IS NOT NULL AND "lastName" = btrim("lastName") AND "lastName" <> \'\' AND "normalizedLastName" = btrim("normalizedLastName") AND "normalizedLastName" <> \'\')',
  ],
  [
    'Person_minimum_identity_check',
    'Person',
    '"nickname" IS NOT NULL OR ("firstName" IS NOT NULL AND "lastName" IS NOT NULL)',
  ],
  ['PersonEmail_version_check', 'PersonEmail', '"version" >= 1'],
  [
    'PersonEmail_values_check',
    'PersonEmail',
    '"email" = btrim("email") AND "email" <> \'\' AND "normalizedEmail" = btrim("normalizedEmail") AND "normalizedEmail" <> \'\' AND "label" = btrim("label") AND "label" <> \'\'',
  ],
  ['PersonPhone_version_check', 'PersonPhone', '"version" >= 1'],
  [
    'PersonPhone_values_check',
    'PersonPhone',
    '"phone" = btrim("phone") AND "phone" <> \'\' AND "normalizedPhone" ~ \'^\\+[1-9][0-9]{1,14}$\' AND "label" = btrim("label") AND "label" <> \'\'',
  ],
  [
    'PersonSocialProfile_version_check',
    'PersonSocialProfile',
    '"version" >= 1',
  ],
  [
    'PersonSocialProfile_network_key_check',
    'PersonSocialProfile',
    '"networkKey" ~ \'^[a-z0-9][a-z0-9_-]{0,39}$\'',
  ],
  [
    'PersonSocialProfile_label_check',
    'PersonSocialProfile',
    '"label" = btrim("label") AND "label" <> \'\'',
  ],
  [
    'PersonSocialProfile_identifier_pair_check',
    'PersonSocialProfile',
    '("identifier" IS NULL AND "normalizedIdentifier" IS NULL) OR ("identifier" IS NOT NULL AND "normalizedIdentifier" IS NOT NULL AND "identifier" = btrim("identifier") AND "identifier" <> \'\' AND "normalizedIdentifier" = btrim("normalizedIdentifier") AND "normalizedIdentifier" <> \'\')',
  ],
  [
    'PersonSocialProfile_url_set_check',
    'PersonSocialProfile',
    '("profileUrl" IS NULL AND "normalizedProfileUrl" IS NULL AND "normalizedProfileUrlHash" IS NULL) OR ("profileUrl" IS NOT NULL AND "normalizedProfileUrl" IS NOT NULL AND "normalizedProfileUrlHash" IS NOT NULL AND "profileUrl" = btrim("profileUrl") AND "profileUrl" <> \'\' AND "normalizedProfileUrl" = btrim("normalizedProfileUrl") AND "normalizedProfileUrl" <> \'\' AND "normalizedProfileUrlHash" ~ \'^[0-9a-f]{64}$\')',
  ],
  [
    'PersonSocialProfile_identifier_or_url_check',
    'PersonSocialProfile',
    '"identifier" IS NOT NULL OR "profileUrl" IS NOT NULL',
  ],
  [
    'PersonDeletionTombstone_values_check',
    'PersonDeletionTombstone',
    '"personId" = btrim("personId") AND "personId" <> \'\' AND "deletionOperationId" = btrim("deletionOperationId") AND "deletionOperationId" <> \'\'',
  ],
  [
    'AuditFieldChange_keys_check',
    'AuditFieldChange',
    '"entityType" ~ \'^[A-Z][A-Z0-9_]{0,39}$\' AND "entityId" = btrim("entityId") AND "entityId" <> \'\' AND "sectionKey" ~ \'^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$\' AND "fieldKey" ~ \'^[A-Za-z0-9][A-Za-z0-9._:-]{0,99}$\' AND ("recordId" IS NULL OR ("recordId" = btrim("recordId") AND "recordId" <> \'\'))',
  ],
  [
    'AuditFieldChange_hashes_check',
    'AuditFieldChange',
    '("beforeHash" IS NULL OR "beforeHash" ~ \'^[0-9a-f]{64}$\') AND ("afterHash" IS NULL OR "afterHash" ~ \'^[0-9a-f]{64}$\')',
  ],
  [
    'AuditFieldChange_storage_check',
    'AuditFieldChange',
    '("valueMode" = \'PLAIN\' AND ("beforeValue" IS NOT NULL OR "afterValue" IS NOT NULL) AND "valuesCiphertext" IS NULL AND "valuesIv" IS NULL AND "valuesAuthTag" IS NULL AND "valueKeyVersion" IS NULL AND "beforeHash" IS NULL AND "afterHash" IS NULL) OR ("valueMode" = \'ENCRYPTED\' AND "beforeValue" IS NULL AND "afterValue" IS NULL AND "valuesCiphertext" IS NOT NULL AND octet_length("valuesCiphertext") BETWEEN 1 AND 8192 AND "valuesIv" IS NOT NULL AND octet_length("valuesIv") = 12 AND "valuesAuthTag" IS NOT NULL AND octet_length("valuesAuthTag") = 16 AND "valueKeyVersion" IS NOT NULL AND "beforeHash" IS NULL AND "afterHash" IS NULL) OR ("valueMode" = \'NONE\' AND "beforeValue" IS NULL AND "afterValue" IS NULL AND "valuesCiphertext" IS NULL AND "valuesIv" IS NULL AND "valuesAuthTag" IS NULL AND "valueKeyVersion" IS NULL)',
  ],
] as const satisfies readonly CheckSpec[];

export const PERSON_SCHEMA_FOREIGN_KEYS = [
  [
    'AuditLog_userId_fkey',
    'AuditLog',
    'userId',
    'User',
    'id',
    'RESTRICT',
    'CASCADE',
  ],
  [
    'AuditLog_targetUserId_fkey',
    'AuditLog',
    'targetUserId',
    'User',
    'id',
    'RESTRICT',
    'CASCADE',
  ],
  [
    'PersonEmail_personId_fkey',
    'PersonEmail',
    'personId',
    'Person',
    'id',
    'CASCADE',
    'CASCADE',
  ],
  [
    'PersonPhone_personId_fkey',
    'PersonPhone',
    'personId',
    'Person',
    'id',
    'CASCADE',
    'CASCADE',
  ],
  [
    'PersonSocialProfile_personId_fkey',
    'PersonSocialProfile',
    'personId',
    'Person',
    'id',
    'CASCADE',
    'CASCADE',
  ],
  [
    'AuditFieldChange_auditLogId_entityType_entityId_fkey',
    'AuditFieldChange',
    'auditLogId,entityType,entityId',
    'AuditLog',
    'id,entityType,entityId',
    'CASCADE',
    'CASCADE',
  ],
  [
    'AuditFieldChange_valueKeyVersion_fkey',
    'AuditFieldChange',
    'valueKeyVersion',
    'AuditEncryptionKeyVersion',
    'version',
    'RESTRICT',
    'CASCADE',
  ],
] as const satisfies readonly ForeignKeySpec[];

export const PERSON_SCHEMA_INDEXES = [
  [
    'AuditLog_id_entityType_entityId_key',
    'AuditLog',
    'btree',
    true,
    'id,entityType,entityId',
    'text_ops,text_ops,text_ops',
    null,
  ],
  [
    'AuditLog_entityType_entityId_createdAt_id_idx',
    'AuditLog',
    'btree',
    false,
    'entityType,entityId,createdAt,id',
    'text_ops,text_ops,timestamp_ops,text_ops',
    null,
  ],
  [
    'PersonEmail_personId_normalizedEmail_key',
    'PersonEmail',
    'btree',
    true,
    'personId,normalizedEmail',
    'text_ops,text_ops',
    null,
  ],
  [
    'PersonEmail_normalizedEmail_idx',
    'PersonEmail',
    'btree',
    false,
    'normalizedEmail',
    'text_ops',
    null,
  ],
  [
    'PersonEmail_normalizedEmail_prefix_idx',
    'PersonEmail',
    'btree',
    false,
    'normalizedEmail',
    'varchar_pattern_ops',
    null,
  ],
  [
    'PersonEmail_one_primary_per_person_idx',
    'PersonEmail',
    'btree',
    true,
    'personId',
    'text_ops',
    'isPrimary = true',
  ],
  [
    'PersonPhone_personId_normalizedPhone_key',
    'PersonPhone',
    'btree',
    true,
    'personId,normalizedPhone',
    'text_ops,text_ops',
    null,
  ],
  [
    'PersonPhone_normalizedPhone_idx',
    'PersonPhone',
    'btree',
    false,
    'normalizedPhone',
    'text_ops',
    null,
  ],
  [
    'PersonPhone_normalizedPhone_prefix_idx',
    'PersonPhone',
    'btree',
    false,
    'normalizedPhone',
    'varchar_pattern_ops',
    null,
  ],
  [
    'PersonPhone_one_primary_per_person_idx',
    'PersonPhone',
    'btree',
    true,
    'personId',
    'text_ops',
    'isPrimary = true',
  ],
  [
    'PersonSocialProfile_person_network_identifier_key',
    'PersonSocialProfile',
    'btree',
    true,
    'personId,networkKey,normalizedIdentifier',
    'text_ops,text_ops,text_ops',
    null,
  ],
  [
    'PersonSocialProfile_person_network_url_hash_key',
    'PersonSocialProfile',
    'btree',
    true,
    'personId,networkKey,normalizedProfileUrlHash',
    'text_ops,text_ops,bpchar_ops',
    null,
  ],
  [
    'PersonSocialProfile_normalizedIdentifier_idx',
    'PersonSocialProfile',
    'btree',
    false,
    'normalizedIdentifier',
    'text_ops',
    null,
  ],
  [
    'PersonSocialProfile_normalizedIdentifier_prefix_idx',
    'PersonSocialProfile',
    'btree',
    false,
    'normalizedIdentifier',
    'varchar_pattern_ops',
    null,
  ],
  [
    'PersonSocialProfile_normalizedProfileUrlHash_idx',
    'PersonSocialProfile',
    'btree',
    false,
    'normalizedProfileUrlHash',
    'bpchar_ops',
    null,
  ],
  [
    'PersonSocialProfile_one_primary_per_network_idx',
    'PersonSocialProfile',
    'btree',
    true,
    'personId,networkKey',
    'text_ops,text_ops',
    'isPrimary = true',
  ],
  [
    'Person_createdAt_id_idx',
    'Person',
    'btree',
    false,
    'createdAt,id',
    'timestamp_ops,text_ops',
    null,
  ],
  [
    'Person_structureStatus_createdAt_id_idx',
    'Person',
    'btree',
    false,
    'structureStatus,createdAt,id',
    'enum_ops,timestamp_ops,text_ops',
    null,
  ],
  [
    'Person_normalizedNickname_trgm_idx',
    'Person',
    'gin',
    false,
    'normalizedNickname',
    'gin_trgm_ops',
    null,
  ],
  [
    'Person_normalizedFirstName_trgm_idx',
    'Person',
    'gin',
    false,
    'normalizedFirstName',
    'gin_trgm_ops',
    null,
  ],
  [
    'Person_normalizedLastName_trgm_idx',
    'Person',
    'gin',
    false,
    'normalizedLastName',
    'gin_trgm_ops',
    null,
  ],
  [
    'Person_normalizedNickname_prefix_idx',
    'Person',
    'btree',
    false,
    'normalizedNickname',
    'varchar_pattern_ops',
    null,
  ],
  [
    'Person_normalizedFirstName_prefix_idx',
    'Person',
    'btree',
    false,
    'normalizedFirstName',
    'varchar_pattern_ops',
    null,
  ],
  [
    'Person_normalizedLastName_prefix_idx',
    'Person',
    'btree',
    false,
    'normalizedLastName',
    'varchar_pattern_ops',
    null,
  ],
  [
    'PersonDeletionTombstone_deletionOperationId_key',
    'PersonDeletionTombstone',
    'btree',
    true,
    'deletionOperationId',
    'text_ops',
    null,
  ],
  [
    'AuditFieldChange_auditLogId_idx',
    'AuditFieldChange',
    'btree',
    false,
    'auditLogId',
    'text_ops',
    null,
  ],
  [
    'AuditFieldChange_history_lookup_idx',
    'AuditFieldChange',
    'btree',
    false,
    'entityType,entityId,sectionKey,fieldKey,recordId,createdAt,id',
    'text_ops,text_ops,text_ops,text_ops,text_ops,timestamp_ops,text_ops',
    null,
  ],
  [
    'AuditFieldChange_valueKeyVersion_idx',
    'AuditFieldChange',
    'btree',
    false,
    'valueKeyVersion',
    'int4_ops',
    null,
  ],
] as const satisfies readonly IndexSpec[];

export const PERSON_SCHEMA_FUNCTIONS = [
  [
    'purge_expired_audit_logs',
    'expected_retention_days integer',
    'bigint',
    true,
    'search_path=pg_catalog, public',
  ],
  [
    'purge_person_audit_field_changes',
    'target_person_id text',
    'bigint',
    true,
    'search_path=pg_catalog, public',
  ],
] as const satisfies readonly FunctionSpec[];

export const PERSON_SCHEMA_TRIGGERS = [
  ['AuditLog_guard_mutation', 'AuditLog', 'guard_audit_log_mutation', 27],
  [
    'AuditFieldChange_validate_parent',
    'AuditFieldChange',
    'validate_audit_field_change_parent',
    7,
  ],
  [
    'AuditFieldChange_guard_mutation',
    'AuditFieldChange',
    'guard_audit_field_change_mutation',
    27,
  ],
  [
    'AuditEncryptionKeyVersion_prevent_mutation',
    'AuditEncryptionKeyVersion',
    'prevent_audit_key_version_mutation',
    27,
  ],
  [
    'PersonDeletionTombstone_prevent_mutation',
    'PersonDeletionTombstone',
    'prevent_person_tombstone_mutation',
    27,
  ],
] as const satisfies readonly TriggerSpec[];
