ALTER TYPE "public"."AuditAction" ADD VALUE 'MFA_ENABLED';
ALTER TYPE "public"."AuditAction" ADD VALUE 'MFA_DISABLED';
ALTER TYPE "public"."AuditAction" ADD VALUE 'MFA_RECOVERY_CODE_USED';
ALTER TYPE "public"."AuditAction" ADD VALUE 'MFA_RECOVERY_CODES_REGENERATED';
